.PHONY: clean All

All:
	@echo "----------Building project:[ RedondeosCronogramas - Debug ]----------"
	@cd "/home/minino/Documentos/Gambas2/00 jsbsan/RedondeosGithub/RedondeosCronogramas/version linux" && "$(MAKE)" -f  "RedondeosCronogramas.mk"
clean:
	@echo "----------Cleaning project:[ RedondeosCronogramas - Debug ]----------"
	@cd "/home/minino/Documentos/Gambas2/00 jsbsan/RedondeosGithub/RedondeosCronogramas/version linux" && "$(MAKE)" -f  "RedondeosCronogramas.mk" clean
